default_language_version:
  python: python3.10
repos:
- hooks:
  - args:
    - --branch=main
    id: no-commit-to-branch
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
- hooks:
  - args:
    - --fix
    id: ruff
    types:
    - python
  repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.2.1
- hooks:
  - id: mypy
    types:
    - python
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
- hooks:
  - id: black
    types:
    - python
  repo: https://github.com/ambv/black
  rev: 24.2.0
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.14.1
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v3.1.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: []
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
