[tool.poetry]
name = "translate-benchmark"
version = "0.1.0"
description = "Translate language model benchmarks."
authors = ["Marten Koopmans <36400337+Mkoopm@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
transformers = "^4.36.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
